name: Publishing
on:
    release:
        types:
            - published
jobs:
    pypi-publish:
        name: PyPI
        if: github.repository_owner == 'juftin'
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/textual-universal-directorytree
        permissions:
            id-token: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.job }}
            cancel-in-progress: false
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install Hatch
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -q hatch pre-commit
                  hatch --version
            - name: Build package
              run: |
                  hatch build
            - name: Publish package on PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
